language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer install --dev --prefer-source

script: vendor/bin/phpunit

notifications:
  email:
    - vincent.composieux@gmail.com
    - andrieu.travail@gmail.com
